// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DataSerialization.AvroAddressBook
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Address : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""Address"",""namespace"":""DataSerialization.AvroAddressBook"",""fields"":[{""name"":""StreetNumber"",""type"":""int""},{""name"":""Street"",""type"":""string""},{""name"":""City"",""type"":""string""},{""name"":""State"",""type"":""string""},{""name"":""Country"",""type"":""string""},{""name"":""PostalCode"",""type"":""int""}]}");
		private int _StreetNumber;
		private string _Street;
		private string _City;
		private string _State;
		private string _Country;
		private int _PostalCode;
		public virtual Schema Schema
		{
			get
			{
				return Address._SCHEMA;
			}
		}
		public int StreetNumber
		{
			get
			{
				return this._StreetNumber;
			}
			set
			{
				this._StreetNumber = value;
			}
		}
		public string Street
		{
			get
			{
				return this._Street;
			}
			set
			{
				this._Street = value;
			}
		}
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				this._City = value;
			}
		}
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				this._State = value;
			}
		}
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				this._Country = value;
			}
		}
		public int PostalCode
		{
			get
			{
				return this._PostalCode;
			}
			set
			{
				this._PostalCode = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.StreetNumber;
			case 1: return this.Street;
			case 2: return this.City;
			case 3: return this.State;
			case 4: return this.Country;
			case 5: return this.PostalCode;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.StreetNumber = (System.Int32)fieldValue; break;
			case 1: this.Street = (System.String)fieldValue; break;
			case 2: this.City = (System.String)fieldValue; break;
			case 3: this.State = (System.String)fieldValue; break;
			case 4: this.Country = (System.String)fieldValue; break;
			case 5: this.PostalCode = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
