// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DataSerialization.AvroAddressBook
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Contact : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""Contact"",""namespace"":""DataSerialization.AvroAddressBook"",""fields"":[{""name"":""Name"",""type"":""string""},{""name"":""Address"",""type"":{""type"":""record"",""name"":""Address"",""namespace"":""DataSerialization.AvroAddressBook"",""fields"":[{""name"":""StreetNumber"",""type"":""int""},{""name"":""Street"",""type"":""string""},{""name"":""City"",""type"":""string""},{""name"":""State"",""type"":""string""},{""name"":""Country"",""type"":""string""},{""name"":""PostalCode"",""type"":""int""}]}},{""name"":""Id"",""type"":""int""},{""name"":""PhoneNumber"",""type"":""int""},{""name"":""Relation"",""type"":{""type"":""enum"",""name"":""Relation"",""namespace"":""DataSerialization.AvroAddressBook"",""symbols"":[""Business"",""Friend"",""Family"",""Aquaintance""]}},{""name"":""Birthday"",""type"":""string""}]}");
		private string _Name;
		private DataSerialization.AvroAddressBook.Address _Address;
		private int _Id;
		private int _PhoneNumber;
		private DataSerialization.AvroAddressBook.Relation _Relation;
		private string _Birthday;
		public virtual Schema Schema
		{
			get
			{
				return Contact._SCHEMA;
			}
		}
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				this._Name = value;
			}
		}
		public DataSerialization.AvroAddressBook.Address Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				this._Address = value;
			}
		}
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public int PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				this._PhoneNumber = value;
			}
		}
		public DataSerialization.AvroAddressBook.Relation Relation
		{
			get
			{
				return this._Relation;
			}
			set
			{
				this._Relation = value;
			}
		}
		public string Birthday
		{
			get
			{
				return this._Birthday;
			}
			set
			{
				this._Birthday = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Name;
			case 1: return this.Address;
			case 2: return this.Id;
			case 3: return this.PhoneNumber;
			case 4: return this.Relation;
			case 5: return this.Birthday;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Name = (System.String)fieldValue; break;
			case 1: this.Address = (DataSerialization.AvroAddressBook.Address)fieldValue; break;
			case 2: this.Id = (System.Int32)fieldValue; break;
			case 3: this.PhoneNumber = (System.Int32)fieldValue; break;
			case 4: this.Relation = (DataSerialization.AvroAddressBook.Relation)fieldValue; break;
			case 5: this.Birthday = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
